# AI CoinJoin Training Configuration

# API Configuration
api:
  blockstream:
    base_url: "https://blockstream.info/api"
    timeout: 10
    rate_limit_delay: 0.5

# Training Parameters
training:
  max_depth: 3
  max_transactions_per_address: 2
  max_addresses_per_tx: 3
  consecutive_normal_limit: 10
  sample_size: 50  # Số lượng transactions để train

# Storage Configuration
storage:
  base_directory: "data/training_results"
  save_only_coinjoin: true
  file_format: "json"

# Investigation Parameters
investigation:
  stopping_conditions:
    consecutive_normal_tx: 10
    no_cluster_connection: true
    max_depth_reached: true

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/training.log"
